### ISSUE TITLE
Handle "Device not found" gracefully

### ISSUE THREAD

**Issue by dbrgn** [lukaspustina/netatmo-rs#2]
When querying the station data for a device ID that does not exist, currently the error is `Error { inner: Error { inner: Error("missing field `body`", line: 1, column: 49) failed to deserialize JSON }`. The body looks like this:

```json
{"error":{"code":9,"message":"Device not found"}}
```

It would be nice if this would be handled more gracefully, e.g. by returning a "device not found" error (or at least an error that contains the error code and message returned by the API) :slightly_smiling_face:

**Comment by lukaspustina** [comment]
I agree.

Can you check if PR #5 suits your requirements!?

**Comment by lukaspustina** [comment]
Perfect. I'll push a new version this week.

**Comment by lukaspustina** [comment]
v0.4.0 just for you :)
