### ISSUE TITLE
Make StationData fields public

### ISSUE THREAD

**Issue by dbrgn** [lukaspustina/netatmo-rs#3]
Right now `StationData` only has private fields, which makes it pretty much useless :slightly_smiling_face:  Or am I missing something?

**Comment by lukaspustina** [comment]
Nope, you're not missing anything unless you just use this library to serialize the data structures with serde. Nevertheless, you're totally right, it really doesn't make sense.

I've just fixed the CI actions and updated the minimum Rust version to 1.38. I've also moved clippy and fmt to the stable channels using almost the default settings.

Please rebase you PR against master -- and be aware of the re-formatting. I'll accept the PR then.

**Comment by dbrgn** [comment]
+1 for rustfmt :slightly_smiling_face:
